openapi: 3.0.3
info:
  title: Lessons Service API
  version: "1.0.0"
  description: |
    OpenAPI specification for the Lessons Service. The generated Swagger UI
    is available at `/swagger-ui.html` when the application is running.
servers:
  - url: http://localhost:8080
    description: Local development
  - url: https://staging.example.com
    description: Staging environment
  - url: https://api.example.com
    description: Production environment
paths:
  /api/tutors:
    get:
      summary: List tutors
      description: Returns all tutors available in the system.
      tags:
        - Tutors
      responses:
        '200':
          description: A list of tutors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tutor'
components:
  schemas:
    Tutor:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        firstName:
          type: string
          example: Maria
        lastName:
          type: string
          example: Ivanova
        subjects:
          type: array
          items:
            type: string
          example:
            - Mathematics
            - Physics
